# GitHub Actions workflow for Node.js 3-Tier App (frontend + backend)
# It checks for syntax errors in JS files during CI

name: 3-Tier GitHub Action CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  compile:
    runs-on: runner-1
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 23
      - name: Frontend compilation (syntax check)
        run: |
          cd client
          find . -name "*.js" -exec node --check {} \;
      - name: Backend compilation (syntax check)
        run: |
          cd api
          find . -name "*.js" -exec node --check {} \;

  
  gitleaks:
    runs-on: runner-1
    needs: compile
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  
      - name: gitleaks setup 
        uses: gitleaks/gitleaks-action@v2

      - name: gitleaks scann
        run: |
          gitleaks detect --source ./client --exit-code 1
          gitleaks detect --source ./api --exit-code 1
  trivy_scan:
    runs-on: runner-1
    needs:  compile
    steps:
      - name: Run Trivy vulnerability scanner in fs mode
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: tabel
          ignore-unfixed: true
          vuln-type: 'os,llibrary'
          severity: 'CRITICAL,HIGH'
          
              
