# GitHub Actions workflow for Node.js 3-Tier App (frontend + backend)
# It checks for syntax errors in JS files during CI

name: 3-Tier GitHub Action CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  compile:
    runs-on: runner-1

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Frontend compilation (syntax check)
        run: |
          cd client
          find . -name "*.js" -exec node --check {} \;

      - name: Backend compilation (syntax check)
        run: |
          cd api
          find . -name "*.js" -exec node --check {} \;
